name: 'vite-plugin-symfony CI'
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src/vite-plugin-symfony

jobs:
  lint:
    name: Eslint and Tsc
    strategy:
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /package.json
            /pnpm-lock.yaml
            /pnpm-workspace.yaml
            /extra/ux-assets
            /src/vite-plugin-symfony
          sparse-checkout-cone-mode: false

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: 'Install JS dependencies'
        run: 'pnpm i --frozen-lockfile'

      - name: 'Eslint'
        run: 'pnpm run lint:check'

      - name: 'Tsc'
        run: 'pnpm run tsc:check'

      - name: 'Test'
        run: 'pnpm run test-run'
